In [2]:
import torch
import numpy as np

In [3]:
action_names = np.load('data/action_names.npy')
action_names

array(['push_side', 'push_top', 'push_front'], dtype='<U10')

In [4]:
action = torch.load('data/img/action.pt')
action

tensor([[ 1., -1., -1.],
        [ 1., -1., -1.],
        [ 1., -1., -1.],
        ...,
        [-1., -1.,  1.],
        [-1., -1.,  1.],
        [-1., -1.,  1.]])

In [5]:
action.shape

torch.Size([2400, 3])

In [6]:
obs_prev_z = torch.load('data/img/obs_prev_z.pt')
obs_prev_z

tensor([[[0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         ...,
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818]],

        [[0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         ...,
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818]],

        [[0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.2818],
         [0.2818, 0.2818, 0.2818,  ..., 0.2818, 0.2818, 0.

In [7]:
obs_prev_z.shape

torch.Size([2400, 42, 42])

In [20]:
obs_prev_z.unsqueeze(1).shape

torch.Size([2400, 1, 42, 42])

In [8]:
obs_prev_z[0].shape

torch.Size([42, 42])

In [9]:
obs_prev_z.flatten(start_dim=1).shape

torch.Size([2400, 1764])

In [10]:
obj_names = np.load('data/obj_names.npy')
obj_names

array(['sphere_9', 'hollow_2', 'cylinderside_9', 'hollow_6', 'cylinder_8',
       'cylinderside_2', 'cylinderside_4', 'sphere_3', 'sphere_6',
       'hollow_5', 'cylinderside_6', 'hollow_3', 'cylinder_2', 'cube_3',
       'cylinder_6', 'cylinder_9', 'cylinderside_1', 'cube_4',
       'cylinderside_7', 'hollow_1', 'cube_2', 'cube_8', 'cylinder_1',
       'cylinder_5', 'hollow_4', 'cylinderside_5', 'cube_9', 'cube_0',
       'cylinder_4', 'hollow_7', 'cube_7', 'cube_5', 'cube_6', 'sphere_2',
       'hollow_8', 'cube_1', 'sphere_4', 'cylinderside_3', 'hollow_9',
       'sphere_0', 'sphere_7', 'sphere_8', 'cylinderside_0', 'sphere_5',
       'hollow_0', 'cylinder_0', 'cylinder_3', 'cylinder_7', 'sphere_1',
       'cylinderside_8'], dtype='<U14')

In [11]:
delta_pix_1 = torch.load('data/img/delta_pix_1.pt')
delta_pix_1

tensor([[12.0000, -1.0000, 27.4719],
        [12.0000, -1.0000, 27.4719],
        [12.0000, -1.0000, 27.4719],
        ...,
        [-1.0000, 32.0000, 18.3615],
        [-1.0000, 32.0000, 18.3615],
        [-1.0000, 32.0000, 18.3615]])

In [12]:
delta_pix_1.shape

torch.Size([2400, 3])

In [13]:
delta_pix_3= torch.load('data/img/delta_pix_1.pt')
delta_pix_3

tensor([[12.0000, -1.0000, 27.4719],
        [12.0000, -1.0000, 27.4719],
        [12.0000, -1.0000, 27.4719],
        ...,
        [-1.0000, 32.0000, 18.3615],
        [-1.0000, 32.0000, 18.3615],
        [-1.0000, 32.0000, 18.3615]])

In [16]:
delta_pix_3.shape

torch.Size([2400, 3])